<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
    <AssemblyTitle>Virtual Drive Manager</AssemblyTitle>
    <Title>Virtual Drive Manager </Title>
    <Authors>Adam Gal</Authors>
    <Copyright>Adam Gal</Copyright>
    <Description>Virtual Drive Manager replacing the Win11 Built In Mounter</Description>
    <!-- Compress runtime for smaller size -->
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="WpfApp1.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

</Project>
